# Este es un flujo de trabajo básico para ayudarlo a comenzar con Acciones 

nombre : Oleoducto 
# Controla cuándo se ejecutará la acción. 
en : 
  # Activa el flujo de trabajo en eventos de solicitud push o pull, pero solo para la rama principal 
  empujar : 
    sucursales : [principal] 
    caminos : 
- Capítulo 15/** 
- .github/workflows/pipeline.yaml 
  # Le permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones 
  flujo de trabajo_despacho : 
# Env para establecer variables reutilizables 
env : 
  ACRNAME : tubería 
# Una ejecución de flujo de trabajo se compone de uno o más trabajos que pueden ejecutarse secuencialmente o en paralelo 
trabajos : 
  # Este flujo de trabajo contiene un solo trabajo llamado "construir" 
  CI : 
    # El tipo de corredor en el que se ejecutará el trabajo 
    se ejecuta en : ubuntu-latest 
    
    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo 
    pasos : 
      # Desprotege su repositorio en $GITHUB_WORKSPACE, para que su trabajo pueda acceder a él 
- nombre : pago de Git 
        usos : acciones/checkout@v2 

- nombre : el inicio de sesión CLI 
        usos : azure/login@v1 
        con : 
          créditos : ${{ secretos.AZURE_CREDENTIALS }} 
      
- nombre : sesión ACR 
        ejecutar : az acr login -n $ACRNAME 
        
      
- nombre : Construir y empujar imagen 
        usos : docker/build-push-action@v2 
        con : 
          contexto : ./Capítulo 15 
          empujar : cierto 
          etiquetas : ${{ env.ACRNAME }}.azurecr.io/website/website:${{ github.run_number }} 
